version: "3.8"

services:
  mysqldb:
    image: mysql:8
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQLDB_DATABASE}"
      MYSQL_USER: "${MYSQLDB_USER}"
      MYSQL_PASSWORD: "${MYSQLDB_PASSWORD}"
    ports:
      - "${MYSQLDB_LOCAL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 3

  bookstore-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    restart: on-failure
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${MYSQLDB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQLDB_PASSWORD}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    depends_on:
      mysqldb:
        condition: service_healthy
